Added namespace support, elephant io fluent api and some fixes
nchaulet/ElephantIOBundle pull request #8
Opened 2016-10-09 16:22 UTC by fractalzombie

2016-10-10 13:43 UTC, nchaulet requested changes

2016-10-10 13:43 UTC, nchaulet commented on .gitignore
> +.idea
I do not think we should add this to this module gitignore

2016-10-10 13:43 UTC, nchaulet commented on Service/Client.php
> +     * @param $namespace
could you fix the doc format is `@param string $namespace`

2016-10-10 13:43 UTC, nchaulet commented on Service/Client.php
> +    public function send($eventName, $data, $namespace = '/')
could you set a default vault to null for namespace and use an if condition after

2016-10-11 01:01 UTC, nchaulet commented
Thanks for the PR 👍

2016-10-12 00:15 UTC, fractalzombie commented
Ok, I will commit changes tomorrow.

2016-10-13 13:03 UTC, fractalzombie commented
I Fix issues

2016-10-14 01:08 UTC, nchaulet commented
Thanks 👍

2016-10-14 01:08 UTC, merged

2016-10-14 01:15 UTC, nchaulet commented
your changes are available in v2.1.0